[package]
name = "ser-hex"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
serde = { version = "1.0.193", features = ["derive"] }
tracing = "0.1.37"
tracing-subscriber = "0.3.17"
tracing-core = { version = "0.1.31", default-features = false }
anyhow = "1.0.75"
serde_json = "1.0.108"

[dev-dependencies]
byteorder = "1.5.0"
